// TraceWebOrigin.generated.swift
// Generated by npm run build (scripts/build.mjs). Do not edit by hand.
// Set TRACE_WEB_ORIGIN in repository root `.env`, then run `npm run build`.

import Foundation

enum TraceWebOriginGenerated {
    /// Same origin injected into Shared (Extension)/Resources/background.js for import / sync.
    static let httpsOrigin: String = "https://www.tracefiction.com"
    /// True only for the exact-origin, dev-only TestFlight onboarding experiment.
    static let allowReleaseExperimentOrigin: Bool = false
}
