// Generated by npm run build (scripts/build.mjs). Do not edit by hand.
globalThis.TRACE_EXTENSION_WEB_ORIGIN = "https://trace-git-dev-zacs-projects-378417c9.vercel.app";
globalThis.TRACE_SESSION_MODE = "kernel";
